CREATE DATABASE IF NOT EXISTS FINSIGNAL_DW;

CREATE SCHEMA IF NOT EXISTS FINSIGNAL_DW.RAW;
CREATE SCHEMA IF NOT EXISTS FINSIGNAL_DW.STAGING;
CREATE SCHEMA IF NOT EXISTS FINSIGNAL_DW.INTERMEDIATE;
CREATE SCHEMA IF NOT EXISTS FINSIGNAL_DW.MARTS;
CREATE SCHEMA IF NOT EXISTS FINSIGNAL_DW.AUDIT;
CREATE SCHEMA IF NOT EXISTS FINSIGNAL_DW.SANDBOX;
